# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        # the name of the "filter set"
        product_thumb :
            # adjust the image quality to 75%
            quality : 75
            filters :
                thumbnail  :
                    size : [261, 261]
                    mode : outbound
        profile_thumb :
            # adjust the image quality to 75%
            quality : 75
            filters :
                thumbnail  :
                    size : [261, 261]
                    mode : outbound